# workflows/build-and-publish.yml
#
# Build and Publish Windows Service
# Automatically build the Fractal Windows Service and publishes via upload to AWS S3.

name: "Build and Publish Windows Service"

on:
    push:
        branches:
            - main
        paths-ignore:
            - "**/README.md"
    workflow_dispatch:

env:
    binary-location: FractalService/bin/Release
    binary-name: FractalService.exe
    s3-bucket-region: us-east-1
    s3-bucket-uri: s3://fractal-windows-service

jobs:
    build-and-publish-main:
        name: Build and Publish Windows Service to AWS S3
        runs-on: windows-2019

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.s3-bucket-region }}

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Install dependencies
              run: dotnet restore

            - name: Restore Nuget Packages
              run: nuget restore FractalService.sln

            - name: Build FractalService Solution
              run: msbuild FractalService.sln -p:Configuration=Release

            - name: Upload binary to S3
              run: aws s3 cp ${{ env.binary-location }}/${{ env.binary-name }} ${{ env.s3-bucket-uri }}/${{ env.binary-name }}

    notify-slack:
        name: Notify Slack
        needs: [build-and-publish-main]
        if: success()
        runs-on: ubuntu-20.04

        steps:
            - name: Notify Slack
              run: |
                  curl -X POST \
                  --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \"Windows Service Pushed to Production via Upload to AWS S3.\", \"icon_emoji\": \":fractal:\"}" \
                  https://hooks.slack.com/services/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
