# Automatically push a new Sentry release

name: Sentry Release

on:
  push:
    branches: [ master, sentry ]
    paths-ignore:
    - '**/README.md'

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: fractalcomputers
      SENTRY_PROJECT: windows-service
      SENTRY_DEPLOY_ENVIRONMENT: production

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Set Git repository URL to enable sentry-cli automatic commit tagging
        run: |
          git remote set-url origin https://github.com/fractalcomputers/windows-service

      - name: Create new Sentry release
        run: |
          # Install Sentry CLI
          curl -sL https://sentry.io/get-cli/ | bash

          # Create new Sentry release
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
          sentry-cli releases set-commits --auto $SENTRY_RELEASE --log-level=debug
          sentry-cli releases finalize $SENTRY_RELEASE

          # Create new deploy for this Sentry release
          sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_DEPLOY_ENVIRONMENT

      - name: Notify Slack
        run: |
          curl -X POST \
          --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Sentry\", \"text\": \"Windows Service Sentry Release pushed to Sentry.\", \"icon_emoji\": \":sentry:\"}" \
          https://hooks.slack.com/services/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
